const preloadUrls = [
  // '/api/curso-{slug}',
  '/api/cursos',
  '/api/cursos-publicados',
  '/api/cursos-substitutos',
  '/api/redirects-cursos',
  '/api/carreiras',
  // '/api/carreira-{slug}',
  '/api/guias',
  // '/api/guia-{code}',
  '/api/formacoes',
  // '/api/formacao-{code}',
  // '/api/formacoes-e-carreiras-de-{categorySlug}',
  // '/api/guia-de-aprendizado/{kindSlug}-{code}',
  // '/api/guia-de-aprendizado/lista-{kindSlug}',
  // '/api/modulo-{moduleCode}',
  // '/api/modulo-{moduleCode}/depoimentos/{quantity}',
  '/api/modulos',
  '/api/categorias',
  // '/api/categoria-{slug}',
  '/api/depoimentos',
  '/api/alura-mais',
  // '/api/alura-mais-{slug}-c{id}',
  // '/api/challenge/{code}',
  '/api/promocoes',
  // '/api/promocoes/{coupon}',
  '/api/v2/promocoes',
  // '/api/v2/promocoes/{coupon}',
  '/api/supercupom',
  '/api/supercupom/renovacao',
  '/api/planos',
  '/api/planos-empresas',
  // '/api/usuario-{username}',
  '/api/instrutores-v2',
  '/api/caelumers',
  '/api/busca/filtros',
  '/api/career-to-category-mapper',
  '/api/degree-to-category-mapper',
  '/api/clear-cache-search-api',
  '/api/home',
  '/api/port-list',
  '/api/segment-list',
  '/api/contact-reasons'
];

export default preloadUrls;
